check50:
  files: &check50_files
    - !exclude "*"
    - !include "*.py"
    - !require hello.py
  checks:
    hello world:
      - run: python3 hello.py
        stdout: Hello, world!
        exit: 0
    Perfect Code:
      - run: cat hello.py
        stdout: print("Hello, world!")
        exit: 0
submit50:
  files: *check50_files
